### PR TITLE
Crud for sponsors

### PR DESCRIPTION
**Pull request by pobrejuanito**
Create, Update, Read All, Read One, Delete One for conference, sponsor, persons, series. Logic to handle hidden fields throughout catalogs mentioned above. For example, whenever a sponsor's hidden field gets updated, an event is fired to update corresponding catalogs to update their "hidden" fields.

### CODE REVIEW

**Comment by pobrejuanito** [comment]
Sure thing!

**Comment by pobrejuanito** [comment]
Aside from technical approach disagreements, is there any other issues that are holding up merging?

**Comment by alangumer** [comment]
Just that the same thing you did in the /admin endpoints to be done in the public endpoints.

**Comment by pobrejuanito** [comment]
> How about the date formating and gell all presenters in the public endpoints?

All the milestones on my statement of work at the moment focuses on admin api functionality. I'll focus on public api afterwards.

**Pull request merged**
