### PR TITLE
CRUD for sermons, stories, audiobooks, scripture songs. Upgrade Laravel & Dingo.

### PR DESCRIPTION
**Pull request by pobrejuanito**
Changes:

- Support for create, update, delete, read for Sermons
- Support for create, update, delete, read for Stories
- Support for create, update, delete, read for Stories
- Support for create, update, delete, read for Audio Books
- Support for create, update, delete, read for Scripture Songs
- Upgrade API to Laravel 5.8 and dingo 2.3.0

### CODE REVIEW

**Comment by avorg** [comment]
Great work.
Few things:
- api/user "404 Not Found", using auth/user "get_class() expects parameter 1 to be object, null given"
- tags/journeys "Call to undefined method App\\TagRecording::recording()"
- Just in case take a look to previous endpoints to make sure they are working.

I noticed that the response for recordings varies for different endpoints, for instance the /presentations endpoint the audio property is an object with the *data* attribute containing the array of audios, whereas the admin/stories/recordings returns the audio array directly without the data object.

**Comment by avorg** [comment]
I noticed that the /admin/presentations is not using the data property to return arrays like presenters, it returns the array directly as the value of **presenters** which I like it more, and not having the extra **data** property. Is it possible to have all the endpoints without the **data** for arrays?

**Comment by pobrejuanito** [comment]
> I noticed that the /admin/presentations is not using the data property to return arrays like presenters, it returns the array directly as the value of **presenters** which I like more, and not having the extra **data** property. Is it possible to have all the endpoints without the **data** prop for arrays?

Yes, I did find out how to remove 'data' namespace, but for the root, dingo seems to then  index the arrays with numbers.
`
{
 "0": [
      {}, {},..
  ]
 "meta": {
  }
}
`

**Comment by pobrejuanito** [comment]
> Great work.
> Few things:
> 
> * api/user "404 Not Found", using auth/user "get_class() expects parameter 1 to be object, null given"
> * tags/journeys "Call to undefined method App\TagRecording::recording()"
> * Just in case take a look to previous endpoints to make sure they are working.
> 
> I noticed that the response for recordings varies for different endpoints, for instance the /presentations endpoint the audio property is an object with the **data** attribute containing the array of audios, whereas the admin/stories/recordings returns the audio array directly without the data object.

Yes, since we haven't merged api for public and admin access, it's currently different. Once we do, it should be the same.

**Comment by pobrejuanito** [comment]
> * api/user "404 Not Found", using auth/user "get_class() expects parameter 1 to be object, null given"

Fixed

**Comment by pobrejuanito** [comment]
> * tags/journeys "Call to undefined method App\TagRecording::recording()"

Fixed

**Pull request merged**
